import 'dart:async';
import 'package:flutter/material.dart';
import '../../core/game/mini_game.dart';

class InvertedFrictionController extends ChangeNotifier implements MiniGame {
  bool _isPlaying = false;
  int _score = 0;
  
  double _yPos = 0.1; // 0.0 top, 1.0 bottom
  double _velocity = 0.002;
  double _heat = 0.0; // Friction heat generated by swiping
  
  Timer? _gameTimer;
  
  double get yPos => _yPos;
  double get heat => _heat;
  bool get isPlaying => _isPlaying;
  @override
  int get score => _score;

  @override
  void start() {
    if (_isPlaying) return;
    _isPlaying = true;
    _reset();
    
    _gameTimer = Timer.periodic(const Duration(milliseconds: 16), (timer) {
      if (!_isPlaying) {
        timer.cancel();
        return;
      }
      _update();
    });
    notifyListeners();
  }

  void _reset() {
    _yPos = 0.1;
    _velocity = 0.002;
    _heat = 0.0;
    _score = 0;
  }

  void swipe() {
    if(!_isPlaying) return;
    // Any swipe adds friction/heat
    _heat = (_heat + 0.2).clamp(0.0, 1.0);
  }

  void _update() {
    // Heat dissipates quickly
    _heat = (_heat - 0.05).clamp(0.0, 1.0);
    
    // Velocity is inversely proportional to Heat
    // Heat 1.0 = Velocity 0.
    // Heat 0.0 = Velocity Normal (or accelerating)
    
    double currentGrav = 0.005 * (1.0 - _heat);
    
    _velocity += currentGrav;
    _velocity *= (1.0 - (_heat * 0.5)); // Drag
    
    _yPos += _velocity;
    
    if (_yPos > 1.2) {
       _reset(); // Fall off
    }
    
    // Check stability (Frozen in mid air)
    if (_heat > 0.8 && _yPos > 0.4 && _yPos < 0.6) {
        _score = 1; // Insight: Keeping it suspended
    }
    notifyListeners();
  }

  @override
  void pause() {
    _isPlaying = false;
    _gameTimer?.cancel();
    notifyListeners();
  }
  @override
  void reset() => start();
  @override
  void dispose() { _gameTimer?.cancel(); super.dispose(); }
}

class InvertedFrictionWidget extends StatelessWidget {
  final InvertedFrictionController controller;
  const InvertedFrictionWidget({super.key, required this.controller});

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: controller,
      builder: (context, child) {
        return GestureDetector(
          onPanUpdate: (_) => controller.swipe(),
          child: Container(
            decoration: BoxDecoration(
                gradient: LinearGradient(
                    colors: [Colors.grey[900]!, Colors.black],
                    begin: Alignment.topCenter, end: Alignment.bottomCenter
                )
            ),
            child: Stack(
              children: [
                // The Orb
                Positioned(
                    top: controller.yPos * MediaQuery.of(context).size.height,
                    left: MediaQuery.of(context).size.width * 0.5 - 25,
                    child: Container(
                        width: 50, height: 50,
                        decoration: BoxDecoration(
                            color: Color.lerp(Colors.blue, Colors.orange, controller.heat),
                            shape: BoxShape.circle,
                            boxShadow: [
                                BoxShadow(
                                    color: Color.lerp(Colors.blue, Colors.red, controller.heat)!.withOpacity(0.8), 
                                    blurRadius: 20 + (controller.heat * 30)
                                )
                            ]
                        ),
                    ),
                ),
                
                if (controller.score > 0)
                   const Center(child: Text("SUSPENDED", style: TextStyle(color: Colors.white, letterSpacing: 8, fontSize: 20))),
              ],
            ),
          ),
        );
      },
    );
  }
}
